"""empty message

Revision ID: 5023529866d6
Revises: c6aeae3e6d54
Create Date: 2020-04-07 18:12:01.966563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5023529866d6'
down_revision = 'c6aeae3e6d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('created_on', sa.Date(), nullable=True))
    op.drop_column('user_profiles', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'created_on')
    # ### end Alembic commands ###
